load("@rules_java//java:defs.bzl", "java_test")

java_test(
  name = "CsvParserTest",
  size = "small",
  srcs = ["CsvParserTest.java"],
  deps = [
    "//java/com/google/location/lbs/activity/audioset/dataprocessing:CsvParser",
    "//third_party/java/junit",
    "//third_party/java/truth/extentions:proto",
   ],